package constant

const (
	PREFIX_API        = "api/v1"
	USER_ROLES_USER   = "1"
	USER_ROLES_ADMIN  = "2"
	USER_ROLES_EXTERN = "3"

	USER_ROLES_USER_INT   = 1
	USER_ROLES_ADMIN_INT  = 2
	USER_ROLES_EXTERN_INT = 3

	APPROVAL_STATUS_REQEUSTED = 1
	APPROVAL_STATUS_APPROVED  = 2
	APPROVAL_STATUS_REJECTED  = 3
	PAYMENT_STATUS_ACTIVE     = 1
	PAYMENT_STATUS_PAID       = 2
	PAYMENT_STATUS_DEFAULTED  = 3
	PAYMENT_STATUS_CANCLED    = 4
)
